import { useState } from 'react';
import { ChevronDown, Search } from 'lucide-react';
import AppLayout from '../layouts/AppLayout';import type{AppPageProps}from'../types';import{card,input,PageHeader}from'./MockUI';
type Row={id:number;name:string;email:string;role:string;status:'Active'|'Inactive'};
const rows:Row[]=[
 {id:1,name:'Sofia Davis',email:'sofia@example.com',role:'Admin',status:'Active'},
 {id:2,name:'Jackson Lee',email:'jackson@example.com',role:'Editor',status:'Inactive'},
 {id:3,name:'Isabella Chen',email:'bella@example.com',role:'Viewer',status:'Active'},
 {id:4,name:'William Kim',email:'william@example.com',role:'Editor',status:'Active'},
 {id:5,name:'Mia Brown',email:'mia@example.com',role:'Viewer',status:'Inactive'},
 {id:6,name:'Lucas Wong',email:'lucas@example.com',role:'Admin',status:'Active'},
];
export default function BasicTables({title}:AppPageProps){const[q,setQ]=useState('');const[sort,setSort]=useState<'asc'|'desc'>('asc');const[page,setPage]=useState(1);const per=4;const data=rows.filter(r=>Object.values(r).some(v=>String(v).toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='asc'?a.name.localeCompare(b.name):b.name.localeCompare(a.name));const total=data.length,pages=Math.max(1,Math.ceil(total/per)),view=data.slice((page-1)*per,page*per);return <AppLayout title={title??'Basic Tables'}><PageHeader title="Basic Tables" subtitle="A searchable, sortable table with pagination."/><div className={`${card} overflow-hidden`}><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Search members..." className={`${input} w-64 pl-9`}/></div><button onClick={()=>setSort(s=>s==='asc'?'desc':'asc')} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm dark:border-gray-700">Name <ChevronDown size={14} className={sort==='asc'?'':'rotate-180'}/></button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500 dark:bg-gray-900"><tr>{['Member','Email','Role','Status'].map(h=><th className="px-5 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody>{view.map(r=><tr key={r.id} className="border-t border-gray-100 dark:border-gray-700"><td className="px-5 py-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-50 text-xs font-semibold text-brand-600">{r.name.split(' ').map(x=>x[0]).join('')}</span><span className="font-medium">{r.name}</span></div></td><td className="px-5 py-3 text-gray-500">{r.email}</td><td className="px-5 py-3"><span className="rounded-full bg-gray-100 px-2 py-0.5 text-xs dark:bg-gray-700">{r.role}</span></td><td className="px-5 py-3"><span className={`rounded-full px-2 py-1 text-xs ${r.status==='Active'?'bg-emerald-50 text-emerald-600':'bg-gray-100 text-gray-500'}`}>{r.status}</span></td></tr>)}</tbody></table></div><div className="flex items-center justify-between p-5 text-sm text-gray-500"><span>Showing {(page-1)*per+1}–{Math.min(page*per,total)} of {total}</span><div className="flex gap-1">{Array.from({length:pages}).map((_,i)=><button key={i} onClick={()=>setPage(i+1)} className={`h-8 w-8 rounded-lg ${page===i+1?'bg-brand-500 text-white':'hover:bg-gray-100 dark:hover:bg-gray-700'}`}>{i+1}</button>)}</div></div></div></AppLayout>}
